#!/usr/bin/env bash
set -euo pipefail
WS="/home/kavia/workspace-code-generation/streamlit-18635-18642/StreamlitFinanceApp"
# ensure python3 venv support (idempotent)
if ! python3 -m venv --help >/dev/null 2>&1; then sudo apt-get update -q >/dev/null && sudo apt-get install -yq python3-venv >/dev/null; fi
PROFILE=/etc/profile.d/streamlit_env.sh
PREFERRED_LOCALE="en_US.UTF-8"
FALLBACK_LOCALE="C.UTF-8"
LOCALE_SELECTED="$FALLBACK_LOCALE"
if command -v locale >/dev/null 2>&1 && locale -a 2>/dev/null | grep -q -F "$PREFERRED_LOCALE"; then LOCALE_SELECTED="$PREFERRED_LOCALE"; fi
# write file with explicit expansion and header; idempotent per-variable
sudo bash -c "cat > '$PROFILE' <<EOF
# Auto-generated by setup (safe to re-run). Exports for headless Streamlit and python behavior.
export STREAMLIT_SERVER_HEADLESS=1
export PYTHONUNBUFFERED=1
export LANG=${LOCALE_SELECTED}
export LC_ALL=${LOCALE_SELECTED}
# Note: LANG may be ineffective if locale is not generated in the container.
EOF"
sudo chmod 644 "$PROFILE"
# export for current session convenience
export STREAMLIT_SERVER_HEADLESS=1 PYTHONUNBUFFERED=1 LANG="$LOCALE_SELECTED" LC_ALL="$LOCALE_SELECTED"
